INSERT INTO LABORDER (ID, description) VALUES (1, 'Simple order');

INSERT INTO LABORDERREPORT (ID, LABORDER_ID) VALUES (1, 1);
INSERT INTO LABORDERREPORT (ID, LABORDER_ID) VALUES (2, 1);
INSERT INTO LABORDERREPORT (ID, LABORDER_ID) VALUES (3, 1);

INSERT INTO LABORDERDETAIL (ID, LABORDER_ID) VALUES (1, 1);

INSERT INTO SUBDETAIL (ID, LABORDERDETAIL_ID) VALUES (1, 1);
INSERT INTO SUBDETAIL (ID, LABORDERDETAIL_ID) VALUES (2, 1);
INSERT INTO SUBDETAIL (ID, LABORDERDETAIL_ID) VALUES (3, 2);
INSERT INTO SUBDETAIL (ID, LABORDERDETAIL_ID) VALUES (4, 2);
INSERT INTO SUBDETAIL (ID, LABORDERDETAIL_ID) VALUES (5, 2);



INSERT INTO LABORDER (ID, description) VALUES (2, 'Simple order 2');

INSERT INTO LABORDERREPORT (ID, LABORDER_ID) VALUES (4, 2);
INSERT INTO LABORDERREPORT (ID, LABORDER_ID) VALUES (5, 2);
INSERT INTO LABORDERREPORT (ID, LABORDER_ID) VALUES (6, 2);


